# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./robot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.commandInput = QtWidgets.QTextEdit(self.centralwidget)
        self.commandInput.setGeometry(QtCore.QRect(120, 400, 670, 121))
        self.commandInput.setObjectName("commandInput")
        self.modeSelector = QtWidgets.QComboBox(self.centralwidget)
        self.modeSelector.setGeometry(QtCore.QRect(15, 400, 90, 30))
        self.modeSelector.setObjectName("modeSelector")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(15, 435, 90, 30))
        self.runButton.setObjectName("runButton")
        self.textOutput = QtWidgets.QTextEdit(self.centralwidget)
        self.textOutput.setGeometry(QtCore.QRect(10, 530, 780, 110))
        self.textOutput.setReadOnly(True)
        self.textOutput.setObjectName("textOutput")
        self.reloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadButton.setGeometry(QtCore.QRect(15, 470, 90, 30))
        self.reloadButton.setObjectName("reloadButton")
        self.imageView = QtWidgets.QLabel(self.centralwidget)
        self.imageView.setGeometry(QtCore.QRect(15, 10, 770, 370))
        self.imageView.setText("")
        self.imageView.setScaledContents(False)
        self.imageView.setAlignment(QtCore.Qt.AlignCenter)
        self.imageView.setObjectName("imageView")
        self.resizeCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.resizeCheck.setGeometry(QtCore.QRect(15, 500, 90, 30))
        self.resizeCheck.setObjectName("resizeCheck")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robot is you GUI"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.reloadButton.setText(_translate("MainWindow", "Reload"))
        self.resizeCheck.setText(_translate("MainWindow", "Resize"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
